### ISSUE TITLE
Home/help/welcome page

### ISSUE THREAD

**Issue by egpickard** [AryamanAgrawal/eat-this#79]
Provide a homepage/help/welcome page because a user wouldn’t inherently know why the dining page is formatted the way it is and how to navigate the site.
Somewhere explain that the dining options are presented based on location + preferences (it is not clear that the dining halls are ordered by location to the user)

**Comment by yehtunkhine** [comment]
-Have a help tab with a "To homepage Button"
-Navigate the user to help tab after sign up
